<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Hangfire" Version="1.8.18" />
      <PackageReference Include="Hangfire.AspNetCore" Version="1.8.18" />
      <PackageReference Include="Hangfire.Redis.StackExchange" Version="1.10.1-beta2" />
      <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
      <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.2" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
      <PackageReference Include="RabbitMQ.Client" Version="7.1.0-alpha.1" />
      <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CourseAppNotificationService_Domain\CourseAppNotificationService_Domain.csproj" />
    </ItemGroup>

</Project>
